"""auto

Revision ID: 042487852bed
Revises: 81bcf8aff3ae
Create Date: 2025-07-07 10:12:14.686130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '042487852bed'
down_revision: Union[str, None] = '81bcf8aff3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_llm', sa.Column('request_body', mysql.MEDIUMTEXT(), nullable=True, comment='분석 request body'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_llm', 'request_body')
    # ### end Alembic commands ###
