"""auto

Revision ID: 08d9d3dea577
Revises: a245d9acf23e
Create Date: 2025-05-16 13:36:26.220663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '08d9d3dea577'
down_revision: Union[str, None] = 'a245d9acf23e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_llm',
    sa.Column('code', sa.String(length=255), nullable=False, comment='LLM 코드 (ex: LLM-GEMINI, LLM-CHATGPT)'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='LLM 이름'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='활성화 여부'),
    sa.Column('priority', mysql.INTEGER(display_width=11), nullable=False, comment='우선순위'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_llm')
    # ### end Alembic commands ###
