"""auto

Revision ID: 2859b54f9841
Revises: ffdd977c6867
Create Date: 2025-08-08 11:06:27.908721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2859b54f9841'
down_revision: Union[str, None] = 'ffdd977c6867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_video_model',
    sa.Column('type', sa.String(length=255), nullable=False, comment='모델 타입 (API, ENGINE)'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='모델 이름'),
    sa.Column('order', sa.SmallInteger(), nullable=True, comment='순서'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_video_model')
    # ### end Alembic commands ###
