"""auto

Revision ID: 2da35a8c269b
Revises: 2859b54f9841
Create Date: 2025-08-21 11:10:54.019728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2da35a8c269b'
down_revision: Union[str, None] = '2859b54f9841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_prompt_assist')
    op.drop_table('resource_engine_role')
    op.drop_table('resource_prompt_language')
    op.drop_table('resource_api_role')
    op.drop_column('resource_analysis', 'role')
    op.drop_column('resource_analysis', 'task_type')
    op.add_column('resource_prompt', sa.Column('analysis_code', sa.String(length=255), nullable=True, comment='분석 코드 (ex: AI-PHOTO2VIDEO-000001)'))
    op.add_column('resource_prompt', sa.Column('group', sa.String(length=255), nullable=True, comment='그룹 (ex: ["10k1m.com"])'))
    op.add_column('resource_prompt', sa.Column('name', sa.String(length=255), nullable=True, comment='프롬프트 이름'))
    op.add_column('resource_prompt', sa.Column('llm_code', sa.String(length=255), nullable=True, comment='LLM 코드 (ex: LLM-CHATGPT)'))
    op.add_column('resource_prompt', sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=True, comment='활성 여부'))
    op.drop_column('resource_prompt', 'system_prompt')
    op.drop_column('resource_prompt', 'api_role_code')
    op.drop_column('resource_prompt', 'is_actvie')
    op.drop_column('resource_prompt', 'order')
    op.add_column('task_llm', sa.Column('prompt', sa.Text(), nullable=True, comment='프롬프트'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_llm', 'prompt')
    op.add_column('resource_prompt', sa.Column('order', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='순서'))
    op.add_column('resource_prompt', sa.Column('is_actvie', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True, comment='활성 여부'))
    op.add_column('resource_prompt', sa.Column('api_role_code', mysql.VARCHAR(length=255), nullable=True, comment='분석 코드 (ex: AI-API-000001)'))
    op.add_column('resource_prompt', sa.Column('system_prompt', mysql.TEXT(), nullable=True, comment='시스템 프롬프트'))
    op.drop_column('resource_prompt', 'is_active')
    op.drop_column('resource_prompt', 'llm_code')
    op.drop_column('resource_prompt', 'name')
    op.drop_column('resource_prompt', 'group')
    op.drop_column('resource_prompt', 'analysis_code')
    op.add_column('resource_analysis', sa.Column('task_type', mysql.VARCHAR(length=255), nullable=True, comment='taks 타입 (engine, api)'))
    op.add_column('resource_analysis', sa.Column('role', mysql.VARCHAR(length=255), nullable=True, comment='분석 role 배열(ex: ["AI-API-ENGINE-000001", "AI-API-ENGINE-000002", "AI-API-ENGINE-000003"])'))
    op.create_table('resource_api_role',
    sa.Column('code', mysql.VARCHAR(length=255), nullable=False, comment='api role 코드 (ex: AI-API-000001)'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True, comment='api 이름 (ex : s3 업로드, 업스테이지, llm ocr 요청)'),
    sa.Column('option', mysql.TEXT(), nullable=True, comment='api 옵션 스키마'),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=True, comment='api 타입 (ex: llm-gemni, upstage )'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True, comment='활성 여부'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('option_example', mysql.TEXT(), nullable=True, comment='api 옵션 예시'),
    sa.Column('end_point', mysql.VARCHAR(length=255), nullable=True, comment='api 엔드포인트'),
    sa.PrimaryKeyConstraint('code'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('resource_prompt_language',
    sa.Column('code', mysql.VARCHAR(length=255), nullable=False, comment='프롬프트 언어 코드 (ex: AI-PROMPT-LANGUAGE-000001)'),
    sa.Column('language', mysql.VARCHAR(length=255), nullable=True, comment='프롬프트 언어'),
    sa.Column('is_actvie', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='활성 여부'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('resource_engine_role',
    sa.Column('code', mysql.VARCHAR(length=255), nullable=False, comment='엔진 role 코드 (ex: AI-ENGINE-000001)'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True, comment='엔진 이름(ex: 문서 요약, 이미지 추출)'),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=True, comment='파일 path'),
    sa.Column('function_name', mysql.VARCHAR(length=255), nullable=True, comment='함수 이름'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True, comment='활성 여부'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=255), server_default=sa.text("'[]'"), nullable=True, comment="엔진 분석 role 배열(ex: ['AI-API-000001', 'AI-API-000002'])"),
    sa.PrimaryKeyConstraint('code'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('resource_prompt_assist',
    sa.Column('code', mysql.VARCHAR(length=255), nullable=False, comment='프롬프트 코드 (ex: AI-ASSIST-PROMPT-000001)'),
    sa.Column('prompt', mysql.TEXT(), nullable=True, comment='프롬프트'),
    sa.Column('input_type', mysql.VARCHAR(length=255), nullable=True, comment='입력 타입'),
    sa.Column('result_type', mysql.VARCHAR(length=255), nullable=True, comment='출력 타입'),
    sa.Column('order', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='순서'),
    sa.Column('is_actvie', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True, comment='활성 여부'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('api_role_code', mysql.VARCHAR(length=255), nullable=True, comment='API role 코드 (ex: AI-API-000001)'),
    sa.PrimaryKeyConstraint('code'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    # ### end Alembic commands ###
