"""auto

Revision ID: 3a1a67e07bdf
Revises: b3875d42419f
Create Date: 2025-04-04 11:08:42.166803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3a1a67e07bdf'
down_revision: Union[str, None] = 'b3875d42419f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_analysis', sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=True, comment='활성 여부'))
    op.drop_column('resource_analysis', 'is_actvie')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_analysis', sa.Column('is_actvie', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True, comment='분석 타입(gg-project)'))
    op.drop_column('resource_analysis', 'is_active')
    # ### end Alembic commands ###
