"""auto

Revision ID: 455f82852c6c
Revises: cec6293c83df
Create Date: 2025-04-03 14:46:07.892851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '455f82852c6c'
down_revision: Union[str, None] = 'cec6293c83df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_api_role',
    sa.Column('code', sa.String(length=255), nullable=False, comment='api role 코드 (ex: AI-API-000001)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='api 이름 (ex : s3 업로드, 업스테이지, llm ocr 요청)'),
    sa.Column('option', sa.Text(), nullable=False, comment='api 옵션 (ex: {"apiKey":"" })'),
    sa.Column('type', sa.String(length=255), nullable=False, comment='api 타입 (ex: llm-gemni, upstage )'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=True, comment='활성 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('resource_engine_role',
    sa.Column('code', sa.String(length=255), nullable=False, comment='엔진 role 코드 (ex: AI-ENGINE-000001)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='엔진 이름(ex: 문서 요약, 이미지 추출)'),
    sa.Column('file_path', sa.String(length=255), nullable=False, comment='파일 path'),
    sa.Column('function_name', sa.String(length=255), nullable=False, comment='함수 이름'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=True, comment='활성 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('resource_prompt',
    sa.Column('code', sa.String(length=255), nullable=False, comment='프롬프트 코드 (ex: AI-PROMPT-000001)'),
    sa.Column('api_role_code', sa.String(length=255), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.Column('is_actvie', sa.Boolean(), server_default=sa.text('1'), nullable=True, comment='분석 타입(gg-project)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.drop_table('resource_llm_assist')
    op.drop_table('prompt')
    op.drop_table('resource_analysis_role')
    op.drop_table('resource_llm')
    op.drop_table('resource_llm_assist_prompt')
    op.add_column('resource_analysis', sa.Column('group', sa.String(length=255), server_default=sa.text("'[]'"), nullable=True, comment='그룹 ["10k1m.com"], [] 빈 배열은 모든 그룹에 처리 가능'))
    op.add_column('resource_analysis', sa.Column('prompt', sa.Text(), nullable=True, comment='프롬프트 임시 칼럼'))
    op.add_column('resource_analysis', sa.Column('is_actvie', sa.Boolean(), server_default=sa.text('1'), nullable=True, comment='분석 타입(gg-project)'))
    op.alter_column('resource_analysis', 'role',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='분석 role 배열(ex: [ANALYSIS-ROLE-000001, ANALYSIS-ROLE-000002, ANALYSIS-ROLE-000003])')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_analysis', 'role',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='분석 role 배열(ex: [ANALYSIS-ROLE-000001, ANALYSIS-ROLE-000002, ANALYSIS-ROLE-000003])')
    op.drop_column('resource_analysis', 'is_actvie')
    op.drop_column('resource_analysis', 'prompt')
    op.drop_column('resource_analysis', 'group')
    op.create_table('resource_llm_assist_prompt',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('assist_code', mysql.VARCHAR(length=255), nullable=False, comment='분석 코드 (ex: LLM-ASSIST-000001)'),
    sa.Column('llm_code', mysql.VARCHAR(length=255), nullable=False, comment='llm 코드 (ex: LLM-GEMINI, LLM-CHATGPT)'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='어시스턴트 이름 (ex: 문서 요약, 맞춤범 검사)'),
    sa.Column('prompt', mysql.TEXT(), nullable=False, comment='어시스턴트 프롬프트'),
    sa.Column('order', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='순서'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('resource_llm',
    sa.Column('code', mysql.VARCHAR(length=255), nullable=False, comment='분석 코드 (ex: LLM-GEMINI, LLM-CHATGPT)'),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False, comment='LLM 이름'),
    sa.Column('option', mysql.VARCHAR(length=255), nullable=False, comment='llm 파라미터'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True, comment='활성화 여부'),
    sa.Column('order', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='순서'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('resource_analysis_role',
    sa.Column('code', mysql.VARCHAR(length=255), nullable=False, comment='분석 role 코드 (ex: ANALYSIS-ROLE-000001)'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='분석 role 이름(ex: llm, 문서 요약, 이미지 추출)'),
    sa.Column('file_name', mysql.VARCHAR(length=255), nullable=False, comment='파일 이름.py'),
    sa.Column('function_name', mysql.VARCHAR(length=255), nullable=False, comment='함수 이름'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='활성 여부'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('prompt',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('group', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('option', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('order', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('system_prompt', mysql.TEXT(), nullable=False),
    sa.Column('prompt', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('resource_llm_assist',
    sa.Column('code', mysql.VARCHAR(length=255), nullable=False, comment='분석 코드 (ex: LLM-ASSIST-000001)'),
    sa.Column('input_type', mysql.VARCHAR(length=255), nullable=False, comment='입력 데이터 형식'),
    sa.Column('result_type', mysql.VARCHAR(length=255), nullable=False, comment='출력 데이터 형식'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True, comment='활성화 여부'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='어시스턴트 이름 (ex: 문서 요약, 맞춤범 검사)'),
    sa.PrimaryKeyConstraint('code'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.drop_table('resource_prompt')
    op.drop_table('resource_engine_role')
    op.drop_table('resource_api_role')
    # ### end Alembic commands ###
