"""auto

Revision ID: 55d21220004f
Revises: b1428791e61c
Create Date: 2025-06-04 14:36:11.707379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55d21220004f'
down_revision: Union[str, None] = 'b1428791e61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_vessl',
    sa.Column('name', sa.String(length=255), nullable=False, comment='vessl 서버 이름'),
    sa.Column('host', sa.String(length=255), nullable=True, comment='서버 ip'),
    sa.Column('port', sa.String(length=255), nullable=True, comment='서버 port'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_vessl')
    # ### end Alembic commands ###
