"""auto

Revision ID: 5c24eddd6d2f
Revises: 8b1ad58e9203
Create Date: 2025-04-10 14:29:35.870146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5c24eddd6d2f'
down_revision: Union[str, None] = '8b1ad58e9203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_prompt_assist',
    sa.Column('code', sa.String(length=255), nullable=False, comment='프롬프트 코드 (ex: AI-ASSIST-PROMPT-000001)'),
    sa.Column('api_role_code', sa.String(length=255), nullable=True, comment='API role 코드 (ex: AI-API-000001)'),
    sa.Column('prompt', sa.Text(), nullable=True, comment='프롬프트'),
    sa.Column('input_type', sa.String(length=255), nullable=True, comment='입력 타입'),
    sa.Column('result_type', sa.String(length=255), nullable=True, comment='출력 타입'),
    sa.Column('order', sa.SmallInteger(), nullable=True, comment='순서'),
    sa.Column('is_actvie', sa.Boolean(), server_default=sa.text('1'), nullable=True, comment='활성 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.add_column('resource_analysis', sa.Column('task_type', sa.String(length=255), nullable=True, comment='taks 타입 (engine, api)'))
    op.alter_column('resource_prompt', 'api_role_code',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='분석 코드 (ex: AI-API-000001)')
    op.alter_column('resource_prompt', 'prompt',
               existing_type=mysql.TEXT(),
               nullable=True,
               existing_comment='프롬프트')
    op.alter_column('resource_prompt', 'order',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True,
               existing_comment='순서')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_prompt', 'order',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False,
               existing_comment='순서')
    op.alter_column('resource_prompt', 'prompt',
               existing_type=mysql.TEXT(),
               nullable=False,
               existing_comment='프롬프트')
    op.alter_column('resource_prompt', 'api_role_code',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='분석 코드 (ex: AI-API-000001)')
    op.drop_column('resource_analysis', 'task_type')
    op.drop_table('resource_prompt_assist')
    # ### end Alembic commands ###
