"""auto

Revision ID: 6091ef856ce4
Revises: e05ad10172b9
Create Date: 2025-06-17 16:00:45.384923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6091ef856ce4'
down_revision: Union[str, None] = 'e05ad10172b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_llm', sa.Column('llm_code', sa.String(length=255), nullable=True, comment='LLM 코드 (ex: LLM-GEMINI, LLM-CHATGPT)'))
    op.add_column('task_llm', sa.Column('llm_end_at', sa.Double(), nullable=True, comment='llm 종료 시간(초)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_llm', 'llm_end_at')
    op.drop_column('task_llm', 'llm_code')
    # ### end Alembic commands ###
