"""auto

Revision ID: 680b2e9ab4d8
Revises: 2da35a8c269b
Create Date: 2025-09-12 14:30:34.483312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '680b2e9ab4d8'
down_revision: Union[str, None] = '2da35a8c269b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_ai_model', 'sqs_queue_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_comment='sqs 큐 배열',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_ai_model', 'sqs_queue_name',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_comment='sqs 큐 배열',
               existing_nullable=True)
    # ### end Alembic commands ###
