"""auto

Revision ID: 6d174abac2d9
Revises: cab44f9966ec
Create Date: 2025-04-17 10:59:27.945978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d174abac2d9'
down_revision: Union[str, None] = 'cab44f9966ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_llm', sa.Column('end_at', sa.String(length=255), nullable=True, comment='종료 시간'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_llm', 'end_at')
    # ### end Alembic commands ###
