"""auto

Revision ID: 712d70212b17
Revises: 9cf5e9458e24
Create Date: 2025-07-22 10:07:16.525456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '712d70212b17'
down_revision: Union[str, None] = '9cf5e9458e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_ai_model',
    sa.Column('code', sa.String(length=255), nullable=False, comment='AI 모델 코드 (ex: AI-MODEL-000001)'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='AI 모델 이름'),
    sa.Column('version', sa.String(length=255), nullable=True, comment='AI 모델 버전'),
    sa.Column('worker_count', mysql.INTEGER(display_width=11), nullable=True, comment='모델 worker 개수'),
    sa.Column('sqs_queue_name', sa.String(length=255), nullable=True, comment='sqs 큐 이름'),
    sa.Column('script', sa.Text(), nullable=True, comment='모델 실행 스크립트'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_ai_model')
    # ### end Alembic commands ###
