"""auto

Revision ID: 81bcf8aff3ae
Revises: 6091ef856ce4
Create Date: 2025-06-20 15:33:49.724694

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81bcf8aff3ae"
down_revision: Union[str, None] = "6091ef856ce4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_llm",
        sa.Column(
            "process", sa.String(length=255), nullable=True, comment="분석 프로세스"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_llm", "process")
    # ### end Alembic commands ###
