"""auto

Revision ID: 89645d3adc5b
Revises: ad1e3412c31b
Create Date: 2025-03-28 17:57:41.555259

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "89645d3adc5b"
down_revision: Union[str, None] = "ad1e3412c31b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resource_llm_assist",
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="어시스턴트 이름 (ex: 문서 요약, 맞춤범 검사)",
        ),
    )
    op.drop_column("resource_llm_assist", "title")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resource_llm_assist",
        sa.Column(
            "title",
            mysql.VARCHAR(length=255),
            nullable=False,
            comment="어시스턴트 이름 (ex: 문서 요약, 맞춤범 검사)",
        ),
    )
    op.drop_column("resource_llm_assist", "name")
    # ### end Alembic commands ###
