"""auto

Revision ID: 8b1ad58e9203
Revises: 3a1a67e07bdf
Create Date: 2025-04-08 17:47:26.972429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8b1ad58e9203'
down_revision: Union[str, None] = '3a1a67e07bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_analysis', 'code',
               existing_type=mysql.VARCHAR(length=255),
               comment='분석 코드 (ex: AI-ANALYSIS-000001)',
               existing_comment='분석 코드 (ex: ANALYSIS-000001)',
               existing_nullable=False)
    op.alter_column('resource_analysis', 'role',
               existing_type=mysql.VARCHAR(length=255),
               comment='분석 role 배열(ex: ["AI-API-ENGINE-000001", "AI-API-ENGINE-000002", "AI-API-ENGINE-000003"])',
               existing_comment='분석 role 배열(ex: [ANALYSIS-ROLE-000001, ANALYSIS-ROLE-000002, ANALYSIS-ROLE-000003])',
               existing_nullable=True)
    op.alter_column('resource_analysis', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='분석 셋 이름 (ex: gemgem 문서 분석용)')
    op.add_column('resource_api_role', sa.Column('option_example', sa.Text(), nullable=True, comment='api 옵션 예시'))
    op.add_column('resource_api_role', sa.Column('end_point', sa.String(length=255), nullable=True, comment='api 엔드포인트'))
    op.alter_column('resource_api_role', 'type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='api 타입 (ex: llm-gemni, upstage )')
    op.alter_column('resource_api_role', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='api 이름 (ex : s3 업로드, 업스테이지, llm ocr 요청)')
    op.alter_column('resource_api_role', 'option',
               existing_type=mysql.TEXT(),
               nullable=True,
               comment='api 옵션 스키마',
               existing_comment='api 옵션 (ex: {"apiKey":"" })')
    op.add_column('resource_engine_role', sa.Column('role', sa.String(length=255), server_default=sa.text("'[]'"), nullable=True, comment="엔진 분석 role 배열(ex: ['AI-API-000001', 'AI-API-000002'])"))
    op.alter_column('resource_engine_role', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='엔진 이름(ex: 문서 요약, 이미지 추출)')
    op.alter_column('resource_engine_role', 'file_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='파일 path')
    op.alter_column('resource_engine_role', 'function_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='함수 이름')
    op.add_column('task_llm', sa.Column('empty_tag', sa.Text(), server_default=sa.text("'[]'"), nullable=True, comment='llm 결과 빈 태그 목록'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_llm', 'empty_tag')
    op.alter_column('resource_engine_role', 'function_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='함수 이름')
    op.alter_column('resource_engine_role', 'file_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='파일 path')
    op.alter_column('resource_engine_role', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='엔진 이름(ex: 문서 요약, 이미지 추출)')
    op.drop_column('resource_engine_role', 'role')
    op.alter_column('resource_api_role', 'option',
               existing_type=mysql.TEXT(),
               nullable=False,
               comment='api 옵션 (ex: {"apiKey":"" })',
               existing_comment='api 옵션 스키마')
    op.alter_column('resource_api_role', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='api 이름 (ex : s3 업로드, 업스테이지, llm ocr 요청)')
    op.alter_column('resource_api_role', 'type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='api 타입 (ex: llm-gemni, upstage )')
    op.drop_column('resource_api_role', 'end_point')
    op.drop_column('resource_api_role', 'option_example')
    op.alter_column('resource_analysis', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='분석 셋 이름 (ex: gemgem 문서 분석용)')
    op.alter_column('resource_analysis', 'role',
               existing_type=mysql.VARCHAR(length=255),
               comment='분석 role 배열(ex: [ANALYSIS-ROLE-000001, ANALYSIS-ROLE-000002, ANALYSIS-ROLE-000003])',
               existing_comment='분석 role 배열(ex: ["AI-API-ENGINE-000001", "AI-API-ENGINE-000002", "AI-API-ENGINE-000003"])',
               existing_nullable=True)
    op.alter_column('resource_analysis', 'code',
               existing_type=mysql.VARCHAR(length=255),
               comment='분석 코드 (ex: ANALYSIS-000001)',
               existing_comment='분석 코드 (ex: AI-ANALYSIS-000001)',
               existing_nullable=False)
    # ### end Alembic commands ###
