"""auto

Revision ID: 9cf5e9458e24
Revises: 042487852bed
Create Date: 2025-07-15 10:07:02.883927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf5e9458e24'
down_revision: Union[str, None] = '042487852bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_engine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='유저 ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='프로젝트 ID'),
    sa.Column('analysis_code', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('progress', sa.SmallInteger(), server_default=sa.text('0'), nullable=True, comment='진행율'),
    sa.Column('process', sa.String(length=255), nullable=False, comment='분석 프로세스'),
    sa.Column('result', sa.Text(), nullable=True, comment='분석 결과'),
    sa.Column('error_code', sa.SmallInteger(), nullable=True, comment='에러 코드'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='에러 메세지'),
    sa.Column('end_at', sa.Double(), nullable=True, comment='종료 시간(초)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_engine')
    # ### end Alembic commands ###
