"""auto

Revision ID: b1428791e61c
Revises: de0a3bedfc85
Create Date: 2025-06-02 14:09:35.130718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1428791e61c'
down_revision: Union[str, None] = 'de0a3bedfc85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_prompt_language',
    sa.Column('code', sa.String(length=255), nullable=False, comment='프롬프트 언어 코드 (ex: AI-PROMPT-LANGUAGE-000001)'),
    sa.Column('language', sa.String(length=255), nullable=True, comment='프롬프트 언어'),
    sa.Column('is_actvie', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='활성 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_prompt_language')
    # ### end Alembic commands ###
