"""auto

Revision ID: b25657273ee5
Revises: effcc3a3fd65
Create Date: 2025-07-25 15:19:04.966606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b25657273ee5'
down_revision: Union[str, None] = 'effcc3a3fd65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_llm', 'error_code',
               existing_type=mysql.SMALLINT(display_width=6),
               type_=sa.String(length=255),
               existing_comment='에러 코드',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_llm', 'error_code',
               existing_type=sa.String(length=255),
               type_=mysql.SMALLINT(display_width=6),
               existing_comment='에러 코드',
               existing_nullable=True)
    # ### end Alembic commands ###
