"""auto

Revision ID: b3875d42419f
Revises: cec0d35fd5f5
Create Date: 2025-04-04 09:28:26.380289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b3875d42419f'
down_revision: Union[str, None] = 'cec0d35fd5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_analysis', 'prompt')
    op.alter_column('resource_prompt', 'api_role_code',
               existing_type=mysql.VARCHAR(length=255),
               comment='분석 코드 (ex: AI-API-000001)',
               existing_nullable=False)
    op.alter_column('resource_prompt', 'system_prompt',
               existing_type=mysql.TEXT(),
               comment='시스템 프롬프트',
               existing_nullable=True)
    op.alter_column('resource_prompt', 'prompt',
               existing_type=mysql.TEXT(),
               comment='프롬프트',
               existing_nullable=False)
    op.alter_column('resource_prompt', 'order',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='순서',
               existing_nullable=False)
    op.alter_column('resource_prompt', 'is_actvie',
               existing_type=mysql.TINYINT(display_width=1),
               comment='활성 여부',
               existing_comment='분석 타입(gg-project)',
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('task_llm', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='유저 ID',
               existing_nullable=False)
    op.alter_column('task_llm', 'project_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='프로젝트 ID',
               existing_nullable=False)
    op.alter_column('task_llm', 'analysis_type',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=255),
               comment='분석 타입 (ex: analysis | llm | assist | crawl)',
               existing_nullable=False)
    op.alter_column('task_llm', 'analysis_code',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('task_llm', 'progress',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True,
               comment='진행율')
    op.alter_column('task_llm', 'result',
               existing_type=mysql.TEXT(),
               comment='분석 결과',
               existing_nullable=True)
    op.alter_column('task_llm', 'error_code',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='에러 코드',
               existing_nullable=True)
    op.alter_column('task_llm', 'error_message',
               existing_type=mysql.VARCHAR(length=255),
               comment='에러 메세지',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_llm', 'error_message',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='에러 메세지',
               existing_nullable=True)
    op.alter_column('task_llm', 'error_code',
               existing_type=mysql.SMALLINT(display_width=6),
               comment=None,
               existing_comment='에러 코드',
               existing_nullable=True)
    op.alter_column('task_llm', 'result',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='분석 결과',
               existing_nullable=True)
    op.alter_column('task_llm', 'progress',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False,
               comment=None,
               existing_comment='진행율')
    op.alter_column('task_llm', 'analysis_code',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('task_llm', 'analysis_type',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='분석 타입 (ex: analysis | llm | assist | crawl)',
               existing_nullable=False)
    op.alter_column('task_llm', 'project_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='프로젝트 ID',
               existing_nullable=False)
    op.alter_column('task_llm', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='유저 ID',
               existing_nullable=False)
    op.alter_column('resource_prompt', 'is_actvie',
               existing_type=mysql.TINYINT(display_width=1),
               comment='분석 타입(gg-project)',
               existing_comment='활성 여부',
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('resource_prompt', 'order',
               existing_type=mysql.SMALLINT(display_width=6),
               comment=None,
               existing_comment='순서',
               existing_nullable=False)
    op.alter_column('resource_prompt', 'prompt',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='프롬프트',
               existing_nullable=False)
    op.alter_column('resource_prompt', 'system_prompt',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='시스템 프롬프트',
               existing_nullable=True)
    op.alter_column('resource_prompt', 'api_role_code',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='분석 코드 (ex: AI-API-000001)',
               existing_nullable=False)
    op.add_column('resource_analysis', sa.Column('prompt', mysql.TEXT(), nullable=True, comment='프롬프트 임시 칼럼'))
    # ### end Alembic commands ###
