"""auto

Revision ID: cab44f9966ec
Revises: 5c24eddd6d2f
Create Date: 2025-04-11 14:54:40.591556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cab44f9966ec'
down_revision: Union[str, None] = '5c24eddd6d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_analysis_type',
    sa.Column('type', sa.String(length=255), nullable=False, comment='분석 타입 (ex: analysis | type | assist | crawl)'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='분석 타입 이름'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_analysis_type')
    # ### end Alembic commands ###
