"""auto

Revision ID: cec0d35fd5f5
Revises: 455f82852c6c
Create Date: 2025-04-04 09:10:07.945748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec0d35fd5f5'
down_revision: Union[str, None] = '455f82852c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_llm', sa.Column('analysis_code', sa.Integer(), nullable=False))
    op.add_column('task_llm', sa.Column('analysis_type', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_llm', 'analysis_type')
    op.drop_column('task_llm', 'analysis_code')
    # ### end Alembic commands ###
