"""auto

Revision ID: cec6293c83df
Revises: 89645d3adc5b
Create Date: 2025-03-31 17:33:04.446754

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cec6293c83df"
down_revision: Union[str, None] = "89645d3adc5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resource_music",
        sa.Column("mood", sa.String(length=255), nullable=True, comment="음악 분위기"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resource_music", "mood")
    # ### end Alembic commands ###
