"""auto

Revision ID: d89a6fc81a1b
Revises: 6d174abac2d9
Create Date: 2025-04-17 17:21:11.098632

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d89a6fc81a1b"
down_revision: Union[str, None] = "6d174abac2d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task_llm",
        "error_message",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_comment="에러 메세지",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task_llm",
        "error_message",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_comment="에러 메세지",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
