"""auto

Revision ID: de0a3bedfc85
Revises: 371a0afa538e
Create Date: 2025-05-28 11:02:47.780546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de0a3bedfc85'
down_revision: Union[str, None] = '371a0afa538e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_ref_image',
    sa.Column('code', sa.String(length=255), nullable=False, comment='레퍼런스 이미지 코드 (ex: AI-REF-IMAGE-000001)'),
    sa.Column('type', sa.String(length=255), nullable=True, comment='레퍼런스 이미지 타입'),
    sa.Column('option', sa.Text(), nullable=True, comment='옵션 json'),
    sa.Column('image_url', sa.Text(), nullable=True, comment='이미지 url'),
    sa.Column('mask_url', sa.Text(), nullable=True, comment='마스크 url'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_ref_image')
    # ### end Alembic commands ###
