"""auto

Revision ID: e05ad10172b9
Revises: 55d21220004f
Create Date: 2025-06-12 17:44:28.837911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e05ad10172b9'
down_revision: Union[str, None] = '55d21220004f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_llm', 'end_at',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Double(),
               comment='종료 시간(초)',
               existing_comment='종료 시간',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_llm', 'end_at',
               existing_type=sa.Double(),
               type_=mysql.VARCHAR(length=255),
               comment='종료 시간',
               existing_comment='종료 시간(초)',
               existing_nullable=True)
    # ### end Alembic commands ###
