"""auto

Revision ID: effcc3a3fd65
Revises: 712d70212b17
Create Date: 2025-07-24 14:57:25.131158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'effcc3a3fd65'
down_revision: Union[str, None] = '712d70212b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_engine', sa.Column('order_no', sa.SmallInteger(), nullable=True, comment='순서'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_engine', 'order_no')
    # ### end Alembic commands ###
