"""auto

Revision ID: ffdd977c6867
Revises: b25657273ee5
Create Date: 2025-07-30 16:36:15.957790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ffdd977c6867'
down_revision: Union[str, None] = 'b25657273ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_llm', sa.Column('llm_result', mysql.MEDIUMTEXT(), nullable=True, comment='llm 결과'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_llm', 'llm_result')
    # ### end Alembic commands ###
