"""auto

Revision ID: 13b10a122502
Revises: 837ca6991f0f
Create Date: 2025-09-03 14:33:16.399029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '13b10a122502'
down_revision: Union[str, None] = '837ca6991f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_worker', 'port',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_comment='worker port',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_worker', 'port',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_comment='worker port',
               existing_nullable=False)
    # ### end Alembic commands ###
