"""auto

Revision ID: 176b6fcc9656
Revises: 
Create Date: 2025-05-02 17:46:59.602202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176b6fcc9656'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_analysis',
    sa.Column('code', sa.String(length=255), nullable=False, comment='분석 코드 (ex: AI-ANALYSIS-000001)'),
    sa.Column('role', sa.String(length=255), server_default=sa.text("'[]'"), nullable=True, comment='분석 role 배열(ex: ["AI-API-ENGINE-000001", "AI-API-ENGINE-000002", "AI-API-ENGINE-000003"])'),
    sa.Column('group', sa.String(length=255), server_default=sa.text("'[]'"), nullable=True, comment='그룹 ["10k1m.com"], [] 빈 배열은 모든 그룹에 처리 가능'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='분석 셋 이름 (ex: gemgem 문서 분석용)'),
    sa.Column('type', sa.String(length=255), nullable=False, comment='분석 타입(gg-project)'),
    sa.Column('task_type', sa.String(length=255), nullable=True, comment='taks 타입 (engine, api)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=True, comment='활성 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('resource_analysis_type',
    sa.Column('type', sa.String(length=255), nullable=False, comment='분석 타입 (ex: analysis | type | assist | crawl)'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='분석 타입 이름'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_analysis_type')
    op.drop_table('resource_analysis')
    # ### end Alembic commands ###
