"""auto

Revision ID: 360ae93fcac8
Revises: c69479dd1d65
Create Date: 2025-08-26 15:51:04.608543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360ae93fcac8'
down_revision: Union[str, None] = 'c69479dd1d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_prompt',
    sa.Column('code', sa.String(length=255), nullable=False, comment='프롬프트 코드 (ex: AI-PROMPT-000001)'),
    sa.Column('analysis_code', sa.String(length=255), nullable=True, comment='분석 코드 (ex: AI-PHOTO2VIDEO-000001)'),
    sa.Column('group', sa.String(length=255), nullable=True, comment='그룹 (ex: ["10k1m.com"])'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='프롬프트 이름'),
    sa.Column('llm_code', sa.String(length=255), nullable=True, comment='LLM 코드 (ex: LLM-CHATGPT)'),
    sa.Column('prompt', sa.Text(), nullable=True, comment='프롬프트'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=True, comment='활성 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_prompt')
    # ### end Alembic commands ###
