"""auto

Revision ID: 3de0e2bcb78f
Revises: b7996c14c8dd
Create Date: 2025-05-14 16:33:43.938747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3de0e2bcb78f'
down_revision: Union[str, None] = 'b7996c14c8dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_music', 'license',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='음악 라이센스')
    op.alter_column('resource_music', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='음악 url (ex: https://cat-10k1m.s3.ap-northeast-2.amazonaws.com/library/sound/bgm/brand/BalloonPlanet-Cool_My_Bass.mp3)')
    op.alter_column('resource_music', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='음악 이름')
    op.alter_column('resource_music', 'duration',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='음악 길이 (초)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_music', 'duration',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='음악 길이 (초)')
    op.alter_column('resource_music', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='음악 이름')
    op.alter_column('resource_music', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='음악 url (ex: https://cat-10k1m.s3.ap-northeast-2.amazonaws.com/library/sound/bgm/brand/BalloonPlanet-Cool_My_Bass.mp3)')
    op.alter_column('resource_music', 'license',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='음악 라이센스')
    # ### end Alembic commands ###
