"""auto

Revision ID: 837ca6991f0f
Revises: 360ae93fcac8
Create Date: 2025-08-28 15:15:52.068658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837ca6991f0f'
down_revision: Union[str, None] = '360ae93fcac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_ai_model',
    sa.Column('code', sa.String(length=255), nullable=False, comment='AI 모델 코드 (ex: AI-MODEL-000001)'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='AI 모델 이름'),
    sa.Column('sqs_queue_name', sa.String(length=255), nullable=True, comment='sqs 큐 배열'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('resource_sqs_queue',
    sa.Column('code', sa.String(length=255), nullable=False, comment='분석 코드 (ex: AI-SQS-000001)'),
    sa.Column('env', sa.String(length=255), nullable=True, comment='운영 환경'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='queue 이름'),
    sa.Column('type', sa.String(length=255), nullable=False, comment='queue 타입'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('resource_worker',
    sa.Column('code', sa.String(length=255), nullable=False, comment='worker 코드 (ex: AI-WORKER-000001)'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='worker 이름'),
    sa.Column('type', sa.String(length=255), nullable=False, comment='worker 타입 api | master | worker'),
    sa.Column('host', sa.String(length=255), nullable=False, comment='worker host'),
    sa.Column('port', sa.String(length=255), nullable=False, comment='worker port'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_worker')
    op.drop_table('resource_sqs_queue')
    op.drop_table('resource_ai_model')
    # ### end Alembic commands ###
