"""auto

Revision ID: b7996c14c8dd
Revises: ddcc8df47751
Create Date: 2025-05-14 15:09:43.965915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b7996c14c8dd'
down_revision: Union[str, None] = 'ddcc8df47751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_music_keyword',
    sa.Column('keyword_id', mysql.INTEGER(display_width=11), nullable=False, comment='키워드 id'),
    sa.Column('keyword_ko', sa.String(length=255), nullable=True, comment='한국어 키워드'),
    sa.Column('keyword_en', sa.String(length=255), nullable=True, comment='영어 키워드'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('keyword_id')
    )
    op.create_table('resource_music_weight',
    sa.Column('music_id', mysql.INTEGER(display_width=11), nullable=False, comment='음악 id'),
    sa.Column('keyword_id', mysql.INTEGER(display_width=11), nullable=False, comment='키워드 id'),
    sa.Column('weight', sa.Float(), nullable=True, comment='가중치'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['resource_music_keyword.keyword_id'], ),
    sa.PrimaryKeyConstraint('music_id', 'keyword_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_music_weight')
    op.drop_table('resource_music_keyword')
    # ### end Alembic commands ###
