"""auto

Revision ID: c69479dd1d65
Revises: ae1eea1b02b6
Create Date: 2025-08-21 09:57:00.898047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c69479dd1d65'
down_revision: Union[str, None] = 'ae1eea1b02b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_analysis', 'task_type')
    op.drop_column('resource_analysis', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_analysis', sa.Column('role', mysql.VARCHAR(length=255), server_default=sa.text("'[]'"), nullable=True, comment='분석 role 배열(ex: ["AI-API-ENGINE-000001", "AI-API-ENGINE-000002", "AI-API-ENGINE-000003"])'))
    op.add_column('resource_analysis', sa.Column('task_type', mysql.VARCHAR(length=255), nullable=True, comment='taks 타입 (engine, api)'))
    # ### end Alembic commands ###
