"""auto

Revision ID: ddcc8df47751
Revises: 176b6fcc9656
Create Date: 2025-05-14 15:09:14.728052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ddcc8df47751'
down_revision: Union[str, None] = '176b6fcc9656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_music',
    sa.Column('music_id', mysql.INTEGER(display_width=11), nullable=False, comment='음악 id'),
    sa.Column('license', sa.String(length=255), nullable=False, comment='음악 라이센스'),
    sa.Column('url', sa.String(length=255), nullable=False, comment='음악 url (ex: https://cat-10k1m.s3.ap-northeast-2.amazonaws.com/library/sound/bgm/brand/BalloonPlanet-Cool_My_Bass.mp3)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='음악 이름'),
    sa.Column('mood', sa.String(length=255), nullable=True, comment='음악 분위기'),
    sa.Column('duration', mysql.INTEGER(display_width=11), nullable=False, comment='음악 길이 (초)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('music_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_music')
    # ### end Alembic commands ###
